### PR TITLE
Run all tests in same workspace (issue #43)

### PR DESCRIPTION
**Pull request by maxbennedich**
A script called [load_modules_for_tests.jl](https://github.com/nep-pack/NonlinearEigenproblems.jl/blob/issue-43-run-tests-in-same-workspace/test/load_modules_for_tests.jl) has been added, which loads all the modules needed for the tests, and sets a global flag `global_modules_loaded`. All tests check whether this flag exists, and if so, do not create a new workspace or load modules. This script is used by the runtests script, but can also be run manually in the REPL to speed up running tests and avoid the "Method definition overwritten" warnings (it only has to be run once per session).

It's quite hacky, but I fear that a cleaner fix would require a lot more work, which will have to be rethought anyway as we migrate to Julia 0.7 (for example, `workspace()` has been removed in 0.7).

With this change, plus changing the Travis build environment to one with more memory, the full build [takes ~7 minutes](https://travis-ci.org/nep-pack/NonlinearEigenproblems.jl/builds/408020028) (of which 4.5 minutes are spent on actual unit tests), compared to [~40 minutes in master](https://travis-ci.org/nep-pack/NonlinearEigenproblems.jl/builds/407945663) (of which 36 minutes are spent on unit tests).

### CODE REVIEW

**Comment by eringh** [comment]
I need to be in the test-folder to run the tests, otherwise I get:
```
julia> include("test/runtests.jl")
All tests: Error During Test
  Got an exception of type SystemError outside of a @test
  SystemError: opening file beyn.jl: No such file or directory
  Stacktrace:
   [1] #systemerror#44 at ./error.jl:64 [inlined]
   [2] systemerror(::String, ::Bool) at ./error.jl:64
   [3] open(::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./iostream.jl:104
   [4] open(::Base.#readstring, ::String) at ./iostream.jl:150
   [5] is_test_script(::String) at /afs/kth.se/home/e/r/eringh/.julia/v0.6/NonlinearEigenproblems/test/runtests.jl:13
   [6] #1 at /afs/kth.se/home/e/r/eringh/.julia/v0.6/NonlinearEigenproblems/test/runtests.jl:30 [inlined]
   [7] filter(::##1#2, ::Array{String,1}) at ./array.jl:1922
   [8] macro expansion at /afs/kth.se/home/e/r/eringh/.julia/v0.6/NonlinearEigenproblems/test/runtests.jl:30 [inlined]
   [9] macro expansion at ./test.jl:860 [inlined]
   [10] anonymous at ./<missing>:?
   [11] include_from_node1(::String) at ./loading.jl:576
   [12] include(::String) at ./sysimg.jl:14
   [13] eval(::Module, ::Any) at ./boot.jl:235
   [14] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
   [15] macro expansion at ./REPL.jl:97 [inlined]
   [16] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
```

Changing line 30 to
```
tests_to_run = filter(f -> is_test_script(joinpath(base_path,f)) && !in(uppercase(f), tests_not_to_run), file_list)
```
fixes the problem for me.

**Comment by eringh** [comment]
So, the  Jacobi–Davidson test fails again...
I am not sure what the difference is between the one that passed [#107](https://travis-ci.org/nep-pack/NonlinearEigenproblems.jl/builds/408020028) and the one that failed [#108](https://travis-ci.org/nep-pack/NonlinearEigenproblems.jl/builds/408029081).
I think we can ignore that for now. Mabe even disable the test that failed. It might also speed up the testing as discussed in issue #43.

**Comment by eringh** [comment]
Changes are not done to files currently not on among the running tests, i.e., `fiber.jl`, `gun.jl`, `matlablinsolvers.jl`, and `Beyn_parallel.jl`. For consistency maybe we should do it for them as well. I can run the tests locally to see that it works.

**Comment by eringh** [comment]
All in all, great work!

**Comment by maxbennedich** [comment]
Thanks for the review! I updated the code and merged the PR.

**Pull request merged**
