### PR TITLE
Deflation rewrite

### LINKED ISSUE #166: Deflation structure preservation
There is room for improvement for our implementation of deflation.  From the "main idea" (my SIAM CSE presentation):  
image

From the main idea one can see that a deflated SPMF can be viewed as a SPMF with extra terms. Therefore, if we apply a deflation to an SPMF (or AbstractSPMF), I think `deflation` should return an  `AbstractSPMF`. Also, when we carry out deflation on a deflated problem, for efficiency reasons we can update the deflation rather than to create recursive structure.

### PR DESCRIPTION
**Pull request by jarlebring**
This fixes #166 and

* Makes deflation more user friendly

* Makes deflation more efficient, in paricular for sparse matrices.

* Makes deflation of a deflated problem not a recursive deflated problem, but just a modified.

* Introduces three deflation modes: Generic, SPMF, MM. SPMF can be used if the SPMF is short and gives a AbstractSPMF. It has some drawbacks in terms of robustness. Generic seems to be the most efficient in many cases. Fits naturally with Juliaesque type-thinking. 

* Updates the deflation tutorial 

**Simulation 1:**
```julia
nep=nep_gallery("dep0_sparse",20);
n=size(nep,1);
local λ,v;
(λ,v)=quasinewton(nep,v=ones(n),λ=3,tol=1e-11,displaylevel=1,maxit=200)
```
```julia
dnep1=deflate_eigpair(nep,λ,v,mode=:Generic);
@btime quasinewton(dnep1,v=ones(size(dnep1,1)),λ=1+1im,tol=1e-11)
```
  2.638 ms (16661 allocations: 3.28 MiB)
```julia
dnep2=deflate_eigpair(nep,λ,v,mode=:SPMF);
@btime quasinewton(dnep2,v=ones(size(dnep1,1)),λ=1+1im,tol=1e-11)
```
  10.774 ms (54923 allocations: 5.88 MiB)

Old approach:
```julia
dnep3=deflate_eigpair(nep,λ,v,mode=:MM);
@btime quasinewton(dnep3,v=ones(size(dnep1,1)),λ=1+1im,tol=1e-11)
```
  6.127 ms (24827 allocations: 4.76 MiB)

**Simulation 2**
If we change to a NEP-solver involving the higher derivatives with `compute_Mder`, we
obtain a much bigger difference:
```julia
nep=nep_gallery("dep0_sparse",100);
n=size(nep,1);
(λ,v)=quasinewton(nep,v=ones(n),λ=2,tol=1e-11,displaylevel=1,maxit=200)
```
```julia
dnep1=deflate_eigpair(nep,λ,v,mode=:Generic);
@btime mslp(dnep1,λ=1im,tol=1e-11)
```
  44.163 ms (3188 allocations: 18.30 MiB)
```julia
dnep2=deflate_eigpair(nep,λ,v,mode=:SPMF);
@btime mslp(dnep2,λ=1im,tol=1e-11)
```
  43.594 ms (4020 allocations: 12.08 MiB)
Old approach:
```julia
dnep3=deflate_eigpair(nep,λ,v,mode=:MM);
@btime mslp(dnep3,λ=1im,tol=1e-11)
```
  426.791 ms (2500 allocations: 101.48 MiB)

**Typical usecase:** 

How to use it to find several eigenvalues:

```julia
  nep=nep_gallery("dep0");
  n=size(nep,1);
  local λ,v;
  (λ,v)=quasinewton(nep,v=ones(n),λ=0,tol=1e-11) # Warmup
  local dnep
  dnep=deflate_eigpair(nep,λ,v,mode=:Generic);
  for k=1:4
      (λ,v)=augnewton(dnep,v=ones(size(dnep,1)),λ=-1+0.1im,
                      tol=1e-11,displaylevel=1,maxit=300,armijo_factor=0.5)
      dnep=deflate_eigpair(dnep,λ,v); # Deflate the computed eigval
  end
  (λv,V)=get_deflated_eigpairs(dnep) # Extract eigpair information
  for k=1:size(λv,1)
     @show norm(compute_Mlincomb(nep,λv[k],V[:,k])) # Prints essentially zeros
  end
```

### CODE REVIEW

**Comment by eringh** [comment]
Potentially we want to move the function `jd_inner_effenberger_linear_solver!` from JD to the deflation. That function uses the `LinSolver` and a Schur complement to solve the associated linear system. What do you think?

**Comment by jarlebring** [comment]
Yes. That code could be useful also outside the context of JD. I view it as a Schur complement linsolver, which is quite natural for the deflated problems. Maybe it should even go to `LinSolvers`. This PR is so big already, and the current setup is not completely wrong, so I would prefer waiting a bit with transferring that code to somewhere more general.

**Comment by eringh** [comment]
Jag har också tittat på en fix för JD. Tror att med den nya strukturen så kan JD utnyttja den bättre.

**Comment by jarlebring** [comment]
Excellent. Just let me merge this PR (a couple of small things remaining).

**Comment by eringh** [comment]
Ok. Then I'll put the JD improvements in a separate PR after this is merged.

**Pull request merged**
