### PR TITLE
Remove functions compute_eigvec_from_eigval

### PR DESCRIPTION
**Pull request by eringh**
Removes code with reference to the discussion in #154, as the `compute_eigvec_from_eigval` was quite a bit of code, did not cover all cases, and was a bit hacky.

### CODE REVIEW

**Comment by jarlebring** [comment]
Nice! 

Merging this will have quite a few conflicts once #168  is merged... so if you need to do more modifications to this PR, it might be good to first sync it with the branch errmeasure_rewrite.

**Comment by eringh** [comment]
I don't think this PR will contain much more. I made it this way to make sure I did not accidentally break something, and to document if we want to go back. We can also wait with merging this until #168 is merged to master (since the latter is more complicated and hence probably nicer to not get merging conflicts). How long do you think that will take?

**Comment by jarlebring** [comment]
:+1:

**Comment by eringh** [comment]
Conflicts resolved. Unfortunately the diff-tool is not very good at seeing what has happened (so the conflicts were also quite messy to resolve). As soon as the tests are ok I'll merge to master.

**Comment by eringh** [comment]
The merge was not nice and this seems to messy to clear out. I will create a new branch from master and do the changes again. It was not that difficult, mostly manual work.

**Pull request closed without merging**
