### PR TITLE
Iar chebyshev test should not mix dense and sparse matrices

### PR DESCRIPTION
**Pull request by maxbennedich**
Cf. discussion in #107

### CODE REVIEW

**Comment by jarlebring** [comment]
:+1:

**Comment by maxbennedich** [comment]
I added a check to enforce that the matrices are either all sparse or all dense, and also ran into some trouble and created a new issue in #114.

**Comment by maxbennedich** [comment]
I also did #114 as part of this PR.

**Comment by jarlebring** [comment]
:+1:

**Pull request merged**
